### PR TITLE
Added androidtv and webos support, added changing volume_entity.

### PR DESCRIPTION
**Pull request by mglants**
Hi there some great staff edited, keys now is global for slider and buttons. 
**Breaking changes added platform.**
volume_entity currently working only for slider

### CODE REVIEW

**Comment by usernein** [comment]
OOOO that's nice!!
Yesterday i discovered that volume slider and touchpad are not working with non-samsung TVs and i was planning to, after fixing that, create a way to make the setup easier for non-samsung TVs. Something like a global service (that all buttons would call), so the users would only need customize the commands/keys at each button.

That's still a good idea but what you did is even better: to add hardcoded support for other integrations

**Comment by MGlants** [comment]
It would be great if u can merge it and release major version

**Comment by MGlants** [comment]
@usernein Please commit or reply

**Comment by usernein** [comment]
Fixed the merge conflicts

**Comment by usernein** [comment]
@MGlants thankss!!

**Pull request merged**
